<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login name_loginname</name>
   <tag></tag>
   <elementGuidId>b3c3dd6b-697a-43d5-a2ab-565c43aa331c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AccountFrm_loginname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccountFrm_loginname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30323f4b-ac5e-438c-9f76-860102bfc5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bfca05f9-8303-4d7b-97cd-0be0cba84c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginname</value>
      <webElementGuid>014c58e2-3d3c-4c67-92d1-67a74f5ad355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountFrm_loginname</value>
      <webElementGuid>55dbf32a-97c0-41f5-8f4c-985963734654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>9bcf356d-c94a-4f5a-af2c-3e106241e0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountFrm_loginname&quot;)</value>
      <webElementGuid>235333fd-9fab-4c83-bcbf-97ec3a1a54b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccountFrm_loginname']</value>
      <webElementGuid>4b9fd0f6-177a-4162-834f-a6741f93549a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AccountFrm']/div[3]/fieldset/div/div/input</value>
      <webElementGuid>076e099a-ae08-471e-83de-567f51579f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div/div/input</value>
      <webElementGuid>e768296d-faf8-4282-a17f-c93f9d64375a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'loginname' and @id = 'AccountFrm_loginname']</value>
      <webElementGuid>51d14f7b-8707-4313-837f-9c4030ff3240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
